In [0]:
import numpy as np

In [15]:
#Numpy array creation using lists
list1=[1,2,3,4]
np_a=np.array(list1)
np_a

array([1, 2, 3, 4])

In [16]:
#Dtype,conver to other data type
np_a=np.array(list1,dtype='object')
np_a.astype('float64')

array([1., 2., 3., 4.])

In [0]:
np_a=np.array([[1,3,4],[5,3,-1]],dtype='object')

In [18]:
np_a.size
np_a.shape
np_a.dtype
np_a.ndim
np_a.itemsize

8

In [19]:
#Boolean Indexing
b=np_a > 2
np_a[b]

array([3, 4, 5, 3], dtype=object)

In [20]:
#For operations involving whole np array use numpy array for which to be calculated
np_a.sum()
np_a.std()

1.9790570145063195

In [21]:
np.amin(np_a,axis=0)
np.cumsum(np_a)
np.amax(np_a,axis=1)

array([4, 5], dtype=object)

In [22]:
#To copy use np.copy()
np_b=np_a.copy()
np_b[1,1]=-10
np_b[1,1] == np_a[1,1]

False

In [23]:
#Reshape 
np_a.reshape(3,-1)

array([[1, 3],
       [4, 5],
       [3, -1]], dtype=object)

In [24]:
#Range elements 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(5,10,2)

array([5, 7, 9])

In [26]:
#Between start and stop with equal spacing of given size 
np.linspace(1,50,10,dtype='float')

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [27]:
np.zeros_like(np_a)

array([[0, 0, 0],
       [0, 0, 0]], dtype=object)

In [28]:
#Random
np.random.randint(10,32,(4,5))

array([[25, 19, 27, 21, 17],
       [24, 30, 18, 16, 17],
       [12, 13, 27, 27, 18],
       [26, 10, 12, 12, 25]])

In [29]:
#Choice 
np_a=np.random.choice(np.random.randint(0,10,size=(10)),size=10,p=(np.zeros((10),dtype='float32')+0.1).tolist())
np_a

array([2, 5, 6, 6, 0, 9, 0, 3, 9, 3])

In [30]:
#Unique returns unique elements and counts of repeating elements
unique,counts=np.unique(np_a,return_counts=True)
for i,j in zip(unique,counts):
  print(i,":",j,end='    ')

0 : 2    2 : 1    3 : 2    5 : 1    6 : 2    9 : 2    

In [31]:
#Where returns flatten indices of true condition 
np_a=np.random.randint(1,10,size=(4,3))
np.random.shuffle(np_a)
ind=np.where(np_a > 5,np_a,-1) #np.where(condition,if present , else)
np_a

array([[8, 7, 3],
       [3, 3, 8],
       [5, 3, 1],
       [4, 3, 8]])

In [32]:
ind

array([[ 8,  7, -1],
       [-1, -1,  8],
       [-1, -1, -1],
       [-1, -1,  8]])

In [33]:
#Location of min and max in array
np.argmax(np_a,axis=1)

array([0, 2, 0, 2])

In [34]:
# Vertical Stack Columns should match vice versa for Horizontal Stack
a=np.zeros((4,5))
b=np.zeros((1,5))
np.vstack((a,b)).shape

(5, 5)

In [35]:
a=np.ones((4,5))
b=np.zeros((4,2))
np.hstack((a,b)).shape

(4, 7)

In [36]:
np.r_[[1,2],4,5,np.ones((5))]

array([1., 2., 4., 5., 1., 1., 1., 1., 1.])

In [37]:
#Ravel() flattens the ndim array into 1D with reference to actual array which is not in case of flatten()
np_a=np.random.randint(1,5,size=(3,2))
a=np_a.flatten()
b=np_a.ravel()
a[1]=10
a[1]==b[1]

False